# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('subtitle', models.CharField(max_length=100, verbose_name='subtitle')),
                ('image', models.ImageField(upload_to=b'media/images/featured/')),
                ('url', models.CharField(max_length=240, verbose_name='url')),
            ],
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=140, verbose_name='name'),
        ),
    ]
