# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160503_1235'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feature',
            new_name='Featured',
        ),
        migrations.AlterModelOptions(
            name='featured',
            options={'verbose_name_plural': 'Featured'},
        ),
    ]
